var panelurl=document.URL;panelurl.match(/ssh-console/g)&&$.getScript("https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js",function(){$.getScript("/scripts/functions.js",function(){$("#win").val($("#cwd").text()+" \n"),$("#command").attr("autocomplete","off").focus(),$("button.clear_cli").click(function(){return $("#win").val($("#cwd").text()+" \n"),$("div.comm_man").hide(),$("#command").val(""),$("#path").val(""),!1}),$("a.opt").click(function(){return $("#command").val($("#command").val()+" "+$(this).attr("href")).focus(),!1}),$("button.comm").click(function(){$("#command").val($(this).val()).focus(),$("div.comm_man").hide();var t="#comm_"+$(this).attr("name");return $(t).show(),!1}),$("#ssh_console").submit(function(){var t=document.getElementById("win");if($("#win").val($("#win").val()+$("#cwd").text()+" "+$("#command").val()+"\n"),"clear"==$("#command").val()||"exit"==$("#command").val())return $("button.clear_cli").trigger("click"),!1;if("cd .."==$("#command").val()){var a=$("#path").val();return a=a.substr(0,a.length-1),a=a.substr(0,a.lastIndexOf("/")),a.length&&(a+="/"),$("#path").val(a),$("#bu").text(a),$("#command").val(""),$("#win").val($("#win").val()+$("#cwd").text()+" \n"),t.scrollTop=99999,!1}return $.ajax({url:$(this).attr("action")+"/format/json",data:{command:$("#command").val(),path:$("#path").val()},dataType:"json",type:"POST",global:!0,timeout:45e3,success:function(a){a.path&&($("#bu").text(a.path),$("#path").val(a.path)),a.response.length>0&&$("#win").val($("#win").val()+a.response+"\n"),$("#win").val($("#win").val()+$("#cwd").text()+"\n"),$("#command").focus().removeAttr("disabled"),t.scrollTop=99999}}),$("#command").val("").attr("disabled","disabled"),t.scrollTop=99999,!1})})});
var panelurl=document.URL;panelurl.match(/webmail/g)&&$("a.redirector").click(function(){var r=$(this).attr("href");$("#prompter").find("form").attr("action",r);$("#prompter").html();return $("#prompter").slideDown(1e3),!1});
var panelurl=document.URL;panelurl.match(/change-language/g)&&$.getScript("https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js",function(){$(document).ready(function(){$("#langselector").click(function(){var a=$('select[name="language"]').val();return $.post("/public/set-language/format/json",{lang:a},function(a){a.success&&location.reload()},"json"),!1})})});
var panelurl=document.URL;panelurl.match(/file-manager/g)&&$.getScript("https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js",function(){$(".insert_title").text("File Manager"),$("#openFM").click(function(){$("#askUserQuestionFormContainer").show("slow"),$('tr[class="odd"]').hide("slow"),$("#askUserQuestionFormContainer").css("text-align","center")})});
var panelurl=document.URL;panelurl.match(/ftp-accounts/g)&&$.getScript("/scripts/treeview/jquery.fbis.treeview.js",function(){$(function(){$("#dir").treeview(null,function(t){var r=$(t.target);$("#directory").val(r.attr("id")),r.parentsUntil("#dir").each(function(t,r){var a=$(r).attr("id");a&&$("#directory").val(a+"/"+$("#directory").val())}),$("#directory").animate({opacity:"0.5"},"fast").animate({opacity:"1"},"fast")})})});
var panelurl=document.URL;panelurl.match(/manager-2/g)&&($(".insert_title").text("FTP Cloud Client"),document.title="CyanDark, Inc. | FTP Cloud Client",$("a.redirector").click(function(){var t=$(this).attr("href");t=t.substring(t.indexOf("username")+9,t.length),$('input[name="username"]').attr("value",t);var n=$(".account-information").text(),e=/Información/,a=e.test(n);return a?$('input[name="ftpserver"]').attr("value",'ftp.'.concat($('.account-information td:contains("Dominio:")').next().text())):$('input[name="ftpserver"]').attr("value",$('.account-information td:contains("Domain:")').next().text()),$("#LoginForm1").slideDown(1e3),!1}));
var panelurl=document.URL;panelurl.match(/start/g)&&($("input[type='radio']").on("ifClicked",function(){$("#solution").removeClass("hide");var e=$(this).val();$("#solution table tr").hide(),$("#sol-"+e).removeClass("hide"),$("#sol-"+e).attr("style","display: block;"),$("#sol-"+e).show(),$("#solution").slideDown(1e3)}),$.getScript("https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js",function(){$.getScript("/scripts/functions.js",function(){var e=$("#searchArticleInput"),i=$("div.questions-block"),t=$("#solution"),s="",l=null,o=null,a=0,n=0,r="";e.focus(),e.live("keyup",function(){if(s!=e.val())for(s=e.val().toLowerCase(),$(t).hide(),a=0;i.length>a;){for(l=$(i[a]).attr("id"),o=$("span[rel="+l+"]"),n=0;o.length>n;)r=$(o[n]).html().toLowerCase(),r.search(s)>=0?(1!=$(i[a]).data("visible")&&($(i[a]).show(),$(i[a]).data("visible",!0)),$(o[n]).show(),$(o[n]).parent().show()):($(o[n]).hide(),$(o[n]).parent().hide()),n++;o=$("span[rel="+l+"]:visible"),o.length<1?($(i[a]).hide(),$(i[a]).data("visible",!1)):($(i[a]).show(),$(i[a]).data("visible",!0)),a++}})})}));
var panelurl=document.URL;if(panelurl.match(/mail-service-control/g)){var text=$(".account-information").text();text.match(/Información/g)?($('input[type="submit"]').css("margin","7px"),$('input[type="submit"]').attr("value","Guardar")):($('input[type="submit"]').css("margin","7px"),$('input[type="submit"]').attr("value","Save"))}
var panelurl=document.URL;if(panelurl.match(/php-configuration/g)){document.title = 'CyanDark, Inc. | PHP'; $('.insert_title').text('PHP');}
var panelurl=document.URL;panelurl.match(/change-theme/g)&&$.getScript("https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js",function(){$("input.themeselector").click(function(){var t=$(this).attr("name");return $.post("/public/set-theme/aid/1925542/format/json",{theme:t},function(t){t.success&&location.reload()},"json"),!1})});

/********* DESIGN ***********/
        var panelurl = document.URL;
        if(panelurl.match(/edit-error-page/g)){ $(function() { CKEDITOR.replace('html_code'); $('form table').css('width', '99.6%'); $('td').css('padding-left', '0px'); $('#cke_html_code').css('width', '100%'); }); }
        if(panelurl.match(/accounts/g) && !panelurl.match(/ftp-accounts/g)){ $('div[class="block top"]').attr('style', 'margin-bottom: 10px;'); $('h2[class="head icon-1"]').attr('style', 'background: #f56954 !important;'); $('.type-1').attr('style', 'border: 1px solid #f56954 !important;'); $('.type-4').attr('style', 'border: 1px solid #f56954 !important;');  $('.type-3').attr('style', 'border: 1px solid #f56954 !important;');}
        if(panelurl.match(/accounts/g) && panelurl.match(/start/g)){ $('div[class="block top"]').attr('style', 'border: 1px solid #f56954 !important;margin-bottom: 10px;'); }
        if(panelurl.match(/accounts/g) && panelurl.match(/upgrade/g)){ $('table[class="type-5"]').attr('style', 'border: 1px solid #f56954 !important;'); }
        if(panelurl.match(/accounts/g) && panelurl.match(/change-theme/g)){ $('h2[class="head icon-8"]').attr('style', 'border: 1px solid #f56954 !important; background: #f56954 !important;'); $('div[class="block"]').attr('style', 'border: 1px solid #f56954 !important;'); }
        if(panelurl.match(/domains/g)){ $('h2[class="head icon-5"]').attr('style', 'border: 1px solid #00a65a !important; background: #00a65a !important;'); $('h2[class="head icon-1"]').attr('style', 'border: 1px solid #00a65a !important; background: #00a65a !important;'); $('table[class="type-4"]').attr('style', 'border: 1px solid #00a65a !important;'); $('table[class="type-5"]').attr('style', 'border: 1px solid #00a65a !important;'); }
        if(panelurl.match(/other/g)){ $('h2[class="head icon-5"]').attr('style', 'border: 1px solid #f39c12 !important; background: #f39c12 !important;'); $('h2[class="head icon-6"]').attr('style', 'border: 1px solid #f39c12 !important; background: #f39c12 !important;'); $('h2[class="head icon-1"]').attr('style', 'border: 1px solid #f39c12 !important; background: #f39c12 !important;'); $('table[class="type-3"]').attr('style', 'border: 1px solid #f39c12 !important;'); $('table[class="type-5"]').attr('style', 'border: 1px solid #f39c12 !important;'); }
        if(panelurl.match(/emails/g)){ $('td[class="t5-left"]').next().attr('style', 'border-right: 1px solid #605ca8 !important;'); $('h2[class="head icon-5"]').attr('style', 'border: 1px solid #605ca8 !important; background: #605ca8 !important;'); $('h2[class="head icon-2"]').attr('style', 'border: 1px solid #605ca8 !important; background: #605ca8 !important;'); $('h2[class="head icon-3"]').attr('style', 'border: 1px solid #605ca8 !important; background: #605ca8 !important;'); $('h2[class="head icon-6"]').attr('style', 'border: 1px solid #605ca8 !important; background: #605ca8 !important;'); $('h2[class="head icon-1"]').attr('style', 'border: 1px solid #605ca8 !important; background: #605ca8 !important;'); $('table[class="type-3"]').attr('style', 'border: 1px solid #605ca8 !important;'); $('table[class="type-1"]').attr('style', 'border: 1px solid #605ca8 !important;'); $('table[class="type-4"]').attr('style', 'border: 1px solid #605ca8 !important;'); $('table[class="type-5"]').attr('style', 'border: 1px solid #605ca8 !important;'); }
        if(panelurl.match(/emails/g) && panelurl.match(/mail-service-control/g)){ $('div[class="block"]').attr('style', 'border: 1px solid #605ca8 !important; padding-bottom: 20px; margin-top: 10px;'); }
        if(panelurl.match(/other/g) && panelurl.match(/password-protect-dirs/g)){$('table[class="type-5"] tr td[colspan="3"]').attr('colspan', '4');}
        if(panelurl.match(/reload-account/g) || panelurl.match(/delete-account/g)){ $('table').attr('style', 'border: 1px solid #f39c12 !important;'); $('input[class="confirm"]').attr('style', 'margin-bottom: 10px; background: #f39c12 !important; border: 1px solid #f39c12;'); }
        if(panelurl.match(/ip-deny/g) || panelurl.match(/fix-file-ownership/g)){ $('.type-3').attr('style', 'border: 1px solid #f39c12 !important; border-top-width: 0px !important;'); $('div[class="block blck2"] p').attr('style', 'border: 1px solid #f39c12 !important; border-bottom-width: 0px !important;'); $('div[class="block"] p').attr('style', 'border: 1px solid #f39c12 !important; border-bottom-width: 0px !important;');}
        if(panelurl.match(/change-password/g) || panelurl.match(/import/g) || panelurl.match(/database-import/g)){ $('.type-3').attr('style', 'border: 1px solid #00c0ef !important; border-top-width: 0px !important;'); $('div[class="block blck2"] p').attr('style', 'border: 1px solid #00c0ef !important; border-bottom-width: 0px !important;'); $('div[class="block"] p').attr('style', 'border: 1px solid #00c0ef !important; border-bottom-width: 0px !important;');}
        if(panelurl.match(/auto-installer/g)){ $('div[class="block blck2"]').attr('style', 'border: 1px solid #00c0ef !important; padding-bottom: 20px; margin-bottom: 10px;').append('<div class="clear"></div>');  $('h2').attr('style', 'margin-top: 0px;'); }
        if(panelurl.match(/ip-deny/g)){$('#ip').attr('placeholder', "___.___.___.___"); $('#ip').attr('class', 'form-control');}
        if(panelurl.match(/website-templates/g) && !panelurl.match(/website-builder/g)){ $('.cony-wrap').attr('style', 'background: #ffffff; margin-left: 5px; overflow: hidden; border: 1px solid #00c0ef !important; border-top-width: 0px !important;'); $('h2[class="head icon-5"] p').attr('style', 'margin-bottom: 5px;');}
        if(panelurl.match(/dns-zone-editor/g)){ $('input[class="button_link_confirm"]').attr('style', 'margin-top: 20px; margin-left: 20px; margin-bottom: 15px; '); }
        if(panelurl.match(/import/g) && panelurl.match(/website/g) && !panelurl.match(/database-import/g)){ $('input[name="archive"]').attr('style', 'border: 2px dashed #0087F7;padding-top: 30px;padding-bottom: 30px;padding-left: 20px;padding-right: 20px;margin-right: -10px;margin-top: -20px;margin-bottom: 20px;'); $('p').attr('style', 'border: 1px solid #00c0ef !important; border-bottom-width: 0px !important; padding-right: 10px;');}
        if(panelurl.match(/ssh-console/g)){ $('form[action="/advanced/ssh-command"]').attr('style', 'border: 1px solid #00c0ef !important; background: #000; margin-top: 7px;'); $('.dark').attr('style', 'border-top-width: 0px;');}
		
if(panelurl.match(/mysql-databases/g)){
	var text = $('.account-information').text(); var pattern = /Información/; var exists = pattern.test(text);
		if(exists){ 
		    var replaced = $('td[class="misc"]').html().replace(/<br>/g,'');
		    $('td[class="misc"]').html(replaced);
			$('td[class="misc"] a:contains("Borrar")').html('<div style="background: #f56954; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-times"></i> Borrar </div>');
			$('td[class="misc"] a:contains("Reparar")').html('<div style="background: #00a65a; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-cogs"></i> Reparar </div>');
			$('td[class="misc"] a:contains("Copia de seguridad")').html('<div style="background: #F09108; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-download"></i> Copia de Seguridad </div>');
			$('td[class="misc"] a:contains("phpMyAdmin")').html('<div style="background: #555; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-th-large"></i> phpMyAdmin </div>');	
		} else { 
		    var replaced = $('td[class="misc"]').html().replace(/<br>/g,'');
		    $('td[class="misc"]').html(replaced);
			$('td[class="misc"] a:contains("Delete")').html('<div style="background: #f56954; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-times"></i> Delete </div>');
			$('td[class="misc"] a:contains("Repair")').html('<div style="background: #00a65a; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-cogs"></i> Repair </div>');
			$('td[class="misc"] a:contains("Backup")').html('<div style="background: #F09108; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-download"></i> Backup </div>');
			$('td[class="misc"] a:contains("phpMyAdmin")').html('<div style="background: #555; padding: 5px; color: #fff !important; font-weight: 600;"><i class="fa fa-fw fa-th-large"></i> phpMyAdmin </div>');	
		}	
}
			
        $('.type-6').removeClass("type-6").addClass('type-4');

/********* SEARCH BOX ***********/
var text = $('.account-information').text(); var pattern = /Información/; var exists = pattern.test(text);

if(exists){ var search = 'Buscar'; 
var mydat = 'Base de Datos MySQL';
var myusr = 'Usuario MySQL';
var myusage = 'Uso, MB';
var actions = 'Acciones';
var subdo = 'Subdominio';
var dir = 'Directorio';
var usr = 'Usuario';
var psw = 'Contraseña';
var blockip = 'IP Bloqueada';
} else { var search = 'Search'; 
var mydat = 'MySQL Database';
var myusr = 'MySQL User';
var myusage = 'Disk Usage, MB';
var actions = 'Actions';
var subdo = 'Subdomain';
var dir = 'Directory';
var usr = 'User';
var psw = 'Password';
var blockip = 'Blocked IP';
}
	
var panelurl=document.URL;
if(panelurl.match(/website/g) && panelurl.match(/auto-installer/g)){ $(".cony-wrap").prepend('<font style="font-size: 20px;">' + search + '</font><hr style=" margin-top: 5px; margin-bottom: 5px; "><div style="padding: 12px; background: #e9eff3; margin: 10px;"><input type="text" id="jquery_search" name="jquery_search" placeholder="' + search + '..." class="form-control"></div> <hr style=" margin-top: 10px; margin-bottom: 10px; ">'); $('input#jquery_search').quicksearch('div[class="block blck2"] a');	 }
if(panelurl.match(/mysql-databases/g)){ $('table[class="type-5"] tbody tr[class="head"]').attr('style', 'display: none;').html(''); $('table[class="type-5"]').prepend('<thead><tr><th colspan="5"><input type="text" id="jquery_search" name="jquery_search" placeholder="' + search + '..." class="form-control" style="margin: 10px; width: 50%; float: right;"></th></tr><tr class="head"><td class="t5-left">'+mydat+'</td><td>'+myusr+'</td><td>MySQL Host</td><td>'+myusage+'</td><td>'+actions+'</td></tr></thead>'); $('input#jquery_search').quicksearch('table[class="type-5"] tbody tr');	 }
if(panelurl.match(/ftp-accounts/g)){ $('table[class="type-5"] tbody tr[class="head"]').attr('style', 'display: none;').html(''); $('table[class="type-5"]').prepend('<thead><tr><th colspan="5"><input type="text" id="jquery_search" name="jquery_search" placeholder="' + search + '..." class="form-control" style="margin: 10px; width: 50%; float: right;"></th></tr><tr class="head"><td class="t5-left">Hostname</td><td>'+dir+'</td><td>'+usr+'</td><td>'+psw+'</td><td>'+actions+'</td></tr></thead>'); $('input#jquery_search').quicksearch('table[class="type-5"] tbody tr');	 }
if(panelurl.match(/subdomains/g)){ $('table[class="type-5"] tbody tr[class="head"]').attr('style', 'display: none;').html(''); $('table[class="type-5"]').prepend('<thead><tr><th colspan="3"><input type="text" id="jquery_search" name="jquery_search" placeholder="' + search + '..." class="form-control" style="margin: 10px; width: 50%; float: right;"></th></tr><tr class="head"><td class="t5-left">'+subdo+'</td><td>'+dir+'</td><td>'+actions+'</td></tr></thead>'); $('input#jquery_search').quicksearch('table[class="type-5"] tbody tr');	 }
if(panelurl.match(/ip-deny/g)){ $('table[class="type-5"] tbody tr[class="head"]').attr('style', 'display: none;').html(''); $('table[class="type-5"]').prepend('<thead><tr><th colspan="2"><input type="text" id="jquery_search" name="jquery_search" placeholder="' + search + '..." class="form-control" style="margin: 10px; width: 50%; float: right;"></th></tr><tr class="head"><td class="t5-left">'+blockip+'</td><td>'+actions+'</td></tr></thead>'); $('input#jquery_search').quicksearch('table[class="type-5"] tbody tr');	 }
if(panelurl.match(/sent-mail-logs/g)){ $(".cony-wrap").prepend('<font style="font-size: 20px;">' + search + '</font><hr style=" margin-top: 5px; margin-bottom: 5px; "><div style="padding: 12px; background: #e9eff3; margin: 10px;"><input type="text" id="jquery_search" name="jquery_search" placeholder="' + search + '..." class="form-control"></div> <hr style=" margin-top: 10px; margin-bottom: 10px; ">'); $('input#jquery_search').quicksearch('div[class="block"] table tbody tr');	 }

